behaviour_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: local_costmap/published_footprint
    local_footprint_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0 #nc
    action_server_result_timeout:
    transform_tolerance: 0.5 #c
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link #c
    behaviour_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviours/Spin"
      simulate_ahead_time: 2.0
      max_rotational_vel: 1.0
      min_rotational_vel: 0.4
      rotational_acc_lim: 3.2
    backup:
      plugin: "nav2_behaviours/BackUp"
      simulate_ahead_time: 2.0
    drive_on_heading:
      plugin: "nav2_behaviours/DriveOnHeading"
      simulate_ahead_time: 2.0
    wait:
      plugin: "nav2_behaviours/Wait"
