global_costmap:
  global_costmap:
    ros_parameters:
    always_send_full_costmap: false
    footprint_padding: 1.1
    footprint: [[-1, -0.55], [-1, 0.55], [1, 0.55], [1, -0.55]]
    update_frequency: 5.0
    publish_frequency: 5.0
    global_frame: map
    height: 10.0
    width: 10.0
    lethal_cost_treshold: 
    map_topic: "map"
    origin_x: 0.0
    origin_y: 0.0
    rolling_window: false
    track_unknown_space: true
    transform_tolerance: 0.5
    initial_transform_timeout: 60.0
    trinary_costmap: true
    unknown_cost_value: 255
    use_maximum: true
    robot_base_frame: base_link
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflaiton_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true #??
      enabled: true #??
      subscribe_to_updates: false #??
      transform_tolerance: 0.5
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true #??
      observation_sources: scan
      footprint_clearing_enabled: true #??
      combination_method: 2
      scan:
        topic: /scan
        obstacle_max_range: 2.5
        obstacle_min_range: 4.0
        raytrace_max_range: 2.5
        raytrace_min_range: 3.5
        expected_update_rate: 12.5
        clearing: true
        marking: true
        data_type: LaserScan
        inf_is_valid: true
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 1.0
      cost_scaling_factor: 1.5
      inflate_unknown: false
      inflate_around_unknown: true

 
    
  
  

  